config/routes.rb
resources :projects do
  put :custom_field_enumerations, :controller => 'project_custom_field_enumerations', action: 'update', as: 'update_custom_field_enumerations'
end
get 'issues/render_form_by_ajax/:id', :controller => 'issues', :action => 'render_form_by_ajax', :as => 'render_form_by_ajax'
get 'issues/load_previous_and_next_issue_ids/:id', to: 'issues#load_previous_and_next_issue_ids', as: :load_previous_and_next_issue_ids
get 'queries/author_values_pagination', :controller => 'queries', :action => 'author_values_pagination', :as => 'author_values_pagination'
get 'queries/assigned_to_values_pagination', :controller => 'queries', :action => 'assigned_to_values_pagination', :as => 'assigned_to_values_pagination'

post 'issues/switch', to: 'issues#switch_display_mode', as: :switch_display_mode

app/models/disabled_custom_field_enumeration.rb
class DisabledCustomFieldEnumeration < ApplicationRecord

  belongs_to :project
  belongs_to :custom_field_enumeration

  def self.disabled_ids_for(project)
    DisabledCustomFieldEnumeration.where(project: project).pluck(:custom_field_enumeration_id)
  end

end

app/controllers/project_custom_field_enumerations_controller.rb
class ProjectCustomFieldEnumerationsController < ApplicationController

  def update
    @project = Project.find(params[:project_id])

    disabled_enumerations_ids = params[:enumerations].select{ |k, v| v == "0" }.keys
    selected_enumerations_ids = params[:enumerations].reject{ |k, v| v == "0" }.keys

    DisabledCustomFieldEnumeration.where(project: @project, custom_field_enumeration_id: selected_enumerations_ids).destroy_all
    disabled_enumerations_ids.each do |custom_field_enumeration_id|
      DisabledCustomFieldEnumeration.find_or_create_by(project: @project, custom_field_enumeration_id: custom_field_enumeration_id)
    end

    respond_to do |format|
      format.html {
        flash[:notice] = l(:notice_successful_update)
        redirect_to settings_project_path(@project, params[:tab])
      }
      format.api  { render_api_ok }
    end
  end

end

app/views/activities/_users.html.erb
<% if !Setting.plugin_redmine_tiny_features['use_select2'] || @project.present? %>

  <%# Standard select tag %>
  <%= select_tag 'user_id',
                 activity_authors_options_for_select(@project, params[:user_id]),
                 include_blank: true %>

<% else %>

  <%# Select2-enhanced select tag for global user selection %>
  <% selected_user = User.find_by(id: params[:user_id]) %>

  <%= select_tag 'user_id',
                 options_for_select([[selected_user&.name, selected_user&.id]].compact, params[:user_id]) %>

  <script>
      document.addEventListener("DOMContentLoaded", function () {
          const $userSelect = $('#user_id');

          if (!$userSelect.length) return;

          $userSelect.select2({
              containerCss: {width: '180px', minWidth: '180px'},
              width: 'style',
              tags: false,
              language: {
                  noResults: () => "Aucun résultat trouvé..",
                  searching: () => "Recherche...",
                  loadingMore: () => "Charger plus de résultats..."
              },
              ajax: {
                  url: '<%= author_values_pagination_path %>',
                  dataType: 'json',
                  delay: 250,
                  method: 'GET',
                  data: params => ({
                      term: params.term,
                      page_limit: 20,
                      page: params.page || 0
                  }),
                  processResults: (data, params) => {
                      params.page = params.page || 0;
                      const maxPage = Math.ceil(data.total / 20);

                      return {
                          results: data.results,
                          pagination: {
                              more:
                                  (params.page * 20 < data.total) &&
                                  (data.results.length < data.total) &&
                                  (maxPage > params.page + 1)
                          }
                      };
                  },
                  cache: true
              }
          });
      });
  </script>

<% end %>

app/views/custom_fields/formats/_range.html.erb
<p>
  <label for="custom_field_min_range"><%=l(:label_min_max_range)%></label>
  <%= f.text_field :min_value, :size => 5, :no_label => true %> -
  <%= f.text_field :max_value, :size => 5, :no_label => true %>
</p>

<p>
  <label for="custom_field_steps"><%=l(:label_steps)%></label>
  <%= f.text_field :steps, :size => 5, :no_label => true %>
</p>
<p>
  <label><%= l(:field_default_value) %></label>
  <%= f.text_field :default_value, :size => 5, :no_label => true %>
</p>

app/views/issues/_edit_closed.html.erb
<% if Setting["plugin_redmine_tiny_features"]["warning_message_on_closed_issues"] == '1' %>

  <% if @issue.closed? %>
    <div id=warning-issue-closed class=warning-issue-closed>
      <p>
        <%= t('warning_closed_issue', link: link_to(t('open_new_issue'), new_issue_path(:project_id => @project))).html_safe %>
      </p>
      <p class="buttons">
        <button><%= t('i_understand') %></button>
      </p>
    </div>
    <script>
        function hideIfIssueClosed() {
            $("#warning-issue-closed").parent().children(".jstElements, .jstEditor, .jstHandle, >p").hide()
            $("#warning-issue-closed").show()
        }

        function showIfIssueOpen() {
            $("#warning-issue-closed").parent().children(".jstElements, .jstEditor, .jstHandle, >p").show()
            $("#warning-issue-closed").hide()
        }

        //on load!
        $(function () {
            hideIfIssueClosed()
            $("#warning-issue-closed button").on("click", function (event) {

                <% if Setting["plugin_redmine_tiny_features"]["open_issue_when_editing_closed_issues"] == '1' %>
                    $('#issue_status_id').val("<%= Setting["plugin_redmine_tiny_features"]["default_open_status"] %>").change()
                <% end %>

                showIfIssueOpen()
                event.preventDefault()
            })
            $("#issue-form").on("change", "#issue_status_id", function () {
                var status_id = parseInt($(this).val())
                if ($.inArray(status_id, <%= IssueStatus.where(:is_closed => true).pluck(:id).inspect %>) < 0) {
                    showIfIssueOpen()
                }
            })
        })
    </script>
  <% end %>

<% end %>

app/views/issues/_load_issue_show_asynchronously.html.erb
<% if Setting.plugin_redmine_tiny_features.key?('load_issue_edit_form_asynchronously') == false %>
  <%= render :partial => 'edit' %>
<% else %>
  <%# These header tags are not included if the partial is not preloaded %>
  <% content_for :header_tags do %>
    <%= javascript_include_tag 'attachments' %>
  <% end %>
  <script>
      function loadIssueEditForm() {
          if ($('#issue-form').length < 1) {
              $.ajax({
                  url: "<%= render_form_by_ajax_path(@issue.id) %>",
                  beforeSend: function () {
                      $('#ajax-indicator').addClass('bottom');
                  },
                  success: function (response) {
                      $('#ajax-indicator').removeClass('bottom');
                      if (response) {
                          $('#update').append(response.html);
                          $(document).ready(function () {
                              // for datepicker element,
                              <% include_calendar_headers_tags %>
                              // for wikitoolbar element in mode Textile,
                              <% heads_for_wiki_formatter %>
                              setupFileDrop();
                              // But for mode visual there is no need to call because it is already called in { $(document).ajaxSuccess/redmine_wysiwyg_editor }
                          });
                      }
                  }, error: function (response) {
                      $('#ajax-indicator').removeClass('bottom');
                      console.error(response);
                  },
              });
          }
      }

      function loadPreviousAndNextIssueIds() {
          $.ajax({
              url: "<%= load_previous_and_next_issue_ids_path(@issue.id) %>",
              success: function (response) {
                  if (response) {
                      $('.issue.details').prepend(response.html);
                  }
              }, error: function (response) {
                  console.error(response);
              },
          });
      }

      $(document).ready(function () {
          loadIssueEditForm();
          loadPreviousAndNextIssueIds();
      });
  </script>
<% end %>

app/views/issues/_previous_and_next_issue_ids.html.erb
<%# Standard Redmine code copied from issues/show.html.erb %>
<%# Must be updated if standard code is updated %>

<% if @prev_issue_id || @next_issue_id %>
  <div class="next-prev-links contextual">
    <%= link_to_if @prev_issue_id,
                   "\xc2\xab #{l(:label_previous)}",
                   (@prev_issue_id ? issue_path(@prev_issue_id) : nil),
                   :title => "##{@prev_issue_id}",
                   :accesskey => accesskey(:previous) %> |
    <% if @issue_position && @issue_count %>
        <span class="position">
          <%= link_to_if @query_path,
                         l(:label_item_position, :position => @issue_position, :count => @issue_count),
                         @query_path %>
        </span> |
    <% end %>
    <%= link_to_if @next_issue_id,
                   "#{l(:label_next)} \xc2\xbb",
                   (@next_issue_id ? issue_path(@next_issue_id) : nil),
                   :title => "##{@next_issue_id}",
                   :accesskey => accesskey(:next) %>
  </div>
<% end %>

app/views/projects/settings/_enumerations.html.erb
<%
  enumerations_custom_fields = @issue_custom_fields.select { |cf| cf.field_format == 'enumeration' }
  project_cfs = @project.all_issue_custom_fields.select { |project_custom_field| enumerations_custom_fields.include? project_custom_field }
  disabled_enumeration_ids = DisabledCustomFieldEnumeration.disabled_ids_for(@project)
%>

<% if project_cfs.present? %>
  <%= form_for :enumerations,
               :method => :put,
               :url => project_update_custom_field_enumerations_path(@project, tab: :enumerations) do |f| %>
    <% project_cfs.each do |custom_field| %>
      <fieldset class="box">
        <legend><%= custom_field_name_tag(custom_field) %></legend>
        <% custom_field.enumerations.active.each do |item| %>
          <%= f.check_box "#{item.id}", {checked: disabled_enumeration_ids.exclude?(item.id), label: item.to_s} %>
          <%= f.label "#{item.id}", item.to_s %>
          <br/>
        <% end %>
      </fieldset>
    <% end %>
    <p><%= submit_tag l(:button_save) %></p>
  <% end %>
<% else %>
  <p><%= l 'no_key_value_custom_field' %></p>
<% end %>

app/views/roles/_general_data.html.erb
<p><h3><%= l(:label_general_data_permission) %></h3></p>
<table class="list permission">
  <thead>
  <tr>
    <th><%= l(:label_general_data) %></th>
    <% @roles.each do |role| %>
      <th>
        <%= content_tag(role.builtin? ? 'em' : 'span', role.name, :class => 'permissions-header') %>
      </th>
    <% end %>
  </tr>
  </thead>
  <tbody>
  <tr class="assignable">
    <td class="name">
      <%= link_to_function('',
                           "toggleCheckboxesBySelector('.assignable input')",
                           :title => "#{l(:button_check_all)}/#{l(:button_uncheck_all)}",
                           :class => 'icon-only icon-checked') %>
      <%= l(:field_assignable) %>
    </td>
    <% @roles.each do |role| %>
      <% if !role.builtin? %>
        <td title="<%= l(:field_assignable) + " (#{role.name})" %>">
          <%= check_box_tag "assignable[#{role.id}][]", 1, (role.assignable), :id => nil %>
        </td>
      <% else %>
        <td></td>
      <% end %>
    <% end %>
  </tr>
  <tr class="group open" class="view_issues_shown">
    <td>
      <span class="expander icon icon-expended" onclick="toggleRowGroup(this);">&nbsp;</span>
      <%= l(:field_issues_visibility) %>
    </td>
    <% @roles.each do |role| %>
      <td class="role"></td>
    <% end %>
  </tr>
  <% Role::ISSUES_VISIBILITY_OPTIONS.each do |option| %>
    <tr class="visibility_<%= option.first %>">
      <td class="name">
        <%= link_to_function('',
                             "toggleCheckboxesBySelector('.visibility_#{option.first} input')",
                             :title => "#{l(:button_check_all)}/#{l(:button_uncheck_all)}",
                             :class => 'icon-only icon-checked') %>
        <%= l(option.second) %>
      </td>
      <% @roles.each do |role| %>
        <td>
          <% unless role.anonymous? %>
            <label class="block">
              <%= radio_button_tag "issues_visibility[#{role.id}]", option.first, role.issues_visibility == option.first, class: "view_issues-#{role.id}_shown"
              %>
            </label>
          <% end %>
        </td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>
<p><h3><%= l(:label_permissions) %></h3></p>

app/views/roles/_trackers_permissions.html.erb
<p><h3><%= l(:label_trackers_permissions) %></h3></p>
</table>
<table class="list trackers-permissions">
  <thead>
  <tr>
    <th><%= l(:label_tracker_all) %></th>
    <% @roles.each do |role| %>
      <th>
        <%= content_tag(role.builtin? ? 'em' : 'span', role.name, :class => 'permissions-header') %>
      </th>
    <% end %>
  </tr>
  </thead>
  <tbody>
  <% permissions = [:view_issues, :add_issues, :edit_issues, :add_issue_notes, :delete_issues] %>
  <% permissions.each do |permission| %>
    <tr class="all-trackers-<%= permission %>">
      <td class="name">
        <%= link_to_function('',
                             "toggleCheckboxesBySelector('tr.all-trackers-#{permission} input[type=checkbox]')",
                             :title => "#{l(:button_check_all)}/#{l(:button_uncheck_all)}",
                             :class => 'icon-only icon-checked') %>
        <%= l("permission_#{permission}") %>
      </td>
      <% @roles.each do |role| %>
        <% if role.has_permission?(permission) && role.setable_permissions.collect(&:name).include?(permission) %>
          <td title="<%= l("permission_#{permission}") + "(#{role.name})" %>">
            <%= hidden_field_tag "permissions_all_trackers[#{role.id}][#{permission}]", '0', :id => nil %>
            <%= check_box_tag "permissions_all_trackers[#{role.id}][#{permission}]", '1', (role.permissions_all_trackers?(permission)), :id => nil, class: "view_issues-#{role.id}_shown", :data => { :disables => ".#{permission}_tracker_role_#{role.id}" } %>
          </td>
        <% else %>
          <td></td>
        <% end %>
        <%= hidden_field_tag "permissions_tracker_ids[#{role.id}][#{permission}][]", '' %>
      <% end %>
    </tr>
  <% end %>
  <% Tracker.sorted.all.each do |tracker| %>
    <tr class="group open">
      <td>
        <span class="expander icon icon-expended" onclick="toggleRowGroup(this);">&nbsp;</span>
        <%= tracker.name %>
      </td>
      <% @roles.each do |role| %>
        <td class="role"><%= role.name %></td>
      <% end %>
    </tr>
    <% permissions.each do |permission| %>
      <tr class="permission-<%= permission %><%= tracker.id %>">
        <td class="name">
          <%= link_to_function('',
                               "toggleCheckboxesBySelector('.permission-#{permission}#{tracker.id} input:enabled')",
                               :title => "#{l(:button_check_all)}/#{l(:button_uncheck_all)}",
                               :class => 'icon-only icon-checked') %>
          <%= l("permission_#{permission}") %>
        </td>
        <% @roles.each do |role| %>
          <% if role.has_permission?(permission) && role.setable_permissions.collect(&:name).include?(permission) %>
            <!--   This condition is because there are (redmine tests) that call the function without passing this parameter -->
            <% if role.permissions_tracker_ids.present? %>
              <td title="<%= l("permission_#{permission}") + "(#{role.name})" %>">
                <%= check_box_tag "permissions_tracker_ids[#{role.id}][#{permission}][]", tracker.id, (role.permissions_tracker_ids[permission].include? tracker.id.to_s), :id => "role_permissions_tracker_ids-#{role.id}_#{tracker.id}", :class => "#{permission}_tracker_role_#{role.id} view_issues-#{role.id}_shown" %>

              </td>
            <% else %>
              <td></td>
            <% end %>
          <% else %>
            <td></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

app/views/settings/_redmine_plugin_tiny_features_settings.html.erb
<p>
  <%= label_tag '', { style: 'width: auto;' } do %>
    <%= check_box_tag "settings[warning_message_on_closed_issues]", '1', Setting["plugin_redmine_tiny_features"]["warning_message_on_closed_issues"] %>
    <%= l("setting_warning_message_on_closed_issues") %>
  <% end %>
</p>
<p>
  <%= label_tag '', { style: 'width: auto;' } do %>
    <%= check_box_tag "settings[open_issue_when_editing_closed_issues]", '1', Setting["plugin_redmine_tiny_features"]["open_issue_when_editing_closed_issues"] %>
    <%= l("setting_open_issue_when_editing_closed_issues") %>
  <% end %>
</p>
<p>
  <%= label_tag l("default_open_status") %>
  <%= select_tag "settings[default_open_status]", options_for_select(IssueStatus.where(is_closed: false).sorted.map { |status| [status.name, status.id] },
                                                                     selected: Setting["plugin_redmine_tiny_features"]["default_open_status"]) %>
</p>

<hr>

<p>
  <%= label_tag '', { style: 'width: auto;' } do %>
    <%= check_box_tag "settings[simplified_version_form]", '1', Setting["plugin_redmine_tiny_features"]["simplified_version_form"] %>
    <%= l("setting_simplified_version_form") %>
  <% end %>
</p>

<hr>

<p>
  <%= label_tag l("default_project") %>
  <%= select_tag "settings[default_project]", project_tree_options_for_select(Project.all_public.active.sorted,
                                                                              selected: Project.where(id: Setting["plugin_redmine_tiny_features"]["default_project"]).first) %>
</p>

<hr>
<% if Redmine::Plugin.installed?(:redmine_base_select2) %>
  <p>
    <%= label_tag '', { style: 'width: auto;' } do %>
      <%= check_box_tag "settings[use_select2]", '1', Setting["plugin_redmine_tiny_features"]["use_select2"], :onclick => "hidePagination()" %>
      <%= l("setting_use_select2") %>
    <% end %>
  </p>

  <p id="paginate_issue_filters_values">
    <%= label_tag '', { style: 'width: auto;' } do %>
      <%= check_box_tag "settings[paginate_issue_filters_values]", '1', Setting["plugin_redmine_tiny_features"]["paginate_issue_filters_values"] %>
      <%= l("setting_paginate_issue_filters_values") %>
    <% end %>
  </p>
<% end %>

<p>
  <%= label_tag '', { style: 'width: auto;text-align:left;' } do %>
    <%= check_box_tag "settings[display_all_users_in_author_filter]", '1', Setting["plugin_redmine_tiny_features"]["display_all_users_in_author_filter"] %>
    <%= l("display_all_users_in_author_filter") %>
  <% end %>
</p>

<hr>

<!-- Added this parameter in order to disable note deletion journalization and do not break core test (JournalsControllerTest#test_update_xhr_with_empty_notes_should_delete_the_journal in redmine core) -->
<p>
  <%= label_tag '', { style: 'width: auto;' } do %>
    <%= check_box_tag "settings[journalize_note_deletion]", '1', Setting["plugin_redmine_tiny_features"]["journalize_note_deletion"] %>
    <%= l("setting_journalize_note_deletion") %>
  <% end %>
</p>


<p>
  <%= label_tag '', { style: 'width: auto;' } do %>
    <%= check_box_tag "settings[disable_email_hiding]", '1', Setting["plugin_redmine_tiny_features"]["disable_email_hiding"] %>
    <%= l("setting_disable_email_hiding") %>
  <% end %>
</p>

<p>
  <%= label_tag '', { style: 'width: auto;' } do %>
    <%= check_box_tag "settings[load_issue_edit_form_asynchronously]", '1', Setting["plugin_redmine_tiny_features"]["load_issue_edit_form_asynchronously"] %>
    <%= l("setting_load_issue_edit_form_asynchronously") %>
  <% end %>
</p>

<p>
  <%= label_tag '', { style: 'width: auto;' } do %>
    <%= check_box_tag "settings[hide_members_section_on_project_overview]", '1', Setting["plugin_redmine_tiny_features"]["hide_members_section_on_project_overview"] %>
    <%= l("hide_members_on_project_overview") %>
  <% end %>
</p>

<p>
  <%= label_tag '', { style: 'width: auto;' } do %>
    <%= check_box_tag "settings[collapse_gantt_chart_at_project_level]", '1', Setting["plugin_redmine_tiny_features"]["collapse_gantt_chart_at_project_level"] %>
    <%= l("collapse_gantt_chart_at_project_level") %>
  <% end %>
</p>

<%= javascript_tag do %>
  $(function() {
  if ((typeof $().select2) === 'function') {
  $('#settings_default_project').select2();
  }
  });

  // Avoid activating pagination if select2 is not active
  function hidePagination(){
  paginationObject = $('#paginate_issue_filters_values input')[0]
  paginationLabel = $('#paginate_issue_filters_values label')[0]
  select2Checked = $('#settings_use_select2')[0].checked

  if(!select2Checked){
  paginationObject.checked = false
  paginationObject.disabled = true
  paginationLabel.classList.add("disabled-settings-redmine-tiny-features")

  } else {
  paginationObject.disabled = false
  paginationLabel.classList.remove("disabled-settings-redmine-tiny-features")
  }
  }

  // Add to disabled option pagination when select2 option is not checked when the page is launched
  hidePagination()
<% end %>

app/views/versions/_form_show_hidden_advanced_fields.html.erb
<% if Setting["plugin_redmine_tiny_features"]["simplified_version_form"] == '1' %>

  <p>
    <a href="#" id="show-hide-advanced-fields">
    <span class="icon icon-toggle-plus" id="show-advanced-fields" style="display: none">
      <%= t("versions_form_show_advanced_fields") %>
    </span>
      <span class="icon icon-toggle-minus" id="hide-advanced-fields" style="display: none">
      <%= t("versions_form_hide_advanced_fields") %>
    </span>
    </a>
  </p>

  <script>
      $(document).ready(function () {
          $("#show-hide-advanced-fields").on("click", function (e) {
              e.preventDefault();
              $("#advanced-fields").toggle();
              if ($("#advanced-fields").is(":visible")) {
                  $("#show-advanced-fields").hide();
                  $("#hide-advanced-fields").show();
              } else {
                  $("#show-advanced-fields").show();
                  $("#hide-advanced-fields").hide();
              }
          });

          $("#show-advanced-fields").show();
          $("<div/>", {id: "advanced-fields"}).hide()
              .appendTo("form.new_version .box.tabular, form.edit_version .box.tabular");
          $("form.new_version, form.edit_version").find(".box.tabular").find("p").each(function () {
              var $this = $(this);
              if (
                  (
                      $this.has("input").length == 1
                      && $this.has("input[name=\"version[name]\"]").length == 0
                  )
                  || $this.has("select").length == 1
              ) {
                  $this.appendTo("#advanced-fields");
              }
          });
      });
  </script>

<% end %>